### ISSUE TITLE
User can see their funds in their account

### ISSUE THREAD

**Issue by ryanjjones10** [ryanjjones10/mm-pay#4]
**Background:**

**Acceptance Criteria:**

```
GIVEN I am on the home page
THEN I can see my account balance in $s and my "Assets"
```

**Dev Notes:**

We are only going to be using USDC testnet tokens so we can use that logo for the tokens

[Designs can be found here](https://www.figma.com/file/JZRFnjQpzxOY2feHZXclnX/Pay?type=design&node-id=18-10905&t=FLLAtxKjbXLwDow1-4)

**Comment by blurpesec** [comment]
Closed by #12
