### ISSUE TITLE
User can create link to send funds

### ISSUE THREAD

**Issue by ryanjjones10** [ryanjjones10/mm-pay#5]
**Background:**

To help with either users that don’t have a wallet or the sender doesn’t know the account number or ENS, individuals have the ability to create a link for anyone to pick up and use.

**Acceptance Criteria:**

```
GIVEN I am on the home page
WHEN I select "Send"
THEN I then can select "Contacts", "Create Link", "Set QR Code"
AND WHEN I select "QR Code"
THEN I can input the amount
AND IF I put more than I have available
THEN I am presented with the error "Insufficient Funds"
AND the button to "Create Link" is grayed out
AND IF I put in less than what I have available
AND WHEN I select "Create Link"
THEN I am presented with the link that I can "Copy" or "Share"
AND When I copy, then it is copied to clipboard
AND When I click Share, it pulls up the mobile apps share functionality
```

**Dev Notes:**

The “Contacts” and “Set QR Code” button do not do anything

For the area that you input your funds, since we only will be using testnet funds on Linea, we can hardcode to their USDC testnet token

[Designs are here](https://www.figma.com/file/JZRFnjQpzxOY2feHZXclnX/Pay?type=design&node-id=18-10905&t=FLLAtxKjbXLwDow1-4)

**Comment by blurpesec** [comment]
Example test claim i used in #17 in order to cover grabbing link and saving:

```typescript
import '@ethersproject/shims'
import { encode } from '@ethersproject/base64'
import { toUtf8Bytes } from '@ethersproject/strings'

export const b64Encode = (value: string) => {
  return encode(toUtf8Bytes(value))
}

export const testClaim = b64Encode(
  JSON.stringify({
    contractAddress: testAddr,
    privateKey: testPrivateKey,
  }),
)
```
